version: "3.8"
services:
  mysql_db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=todos-db
      - MYSQL_USER=user123
      - MYSQL_PASSWORD=user123
      - MYSQL_ROOT_PASSWORD=root123
    ports:
      - 3306:3306
    networks:
      - expense-tracker
  backend-api:
    build:
      context: ../expense-tracker-api
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mysql_db
    networks:
      - expense-tracker
  reverse-proxy:
    build:
      context: docker/nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    networks:
      - expense-tracker
    environment:
      - NGINX_PORT="80"
      - API_HOST_URL
    depends_on:
      - backend-api
networks:
  expense-tracker:
    name: expense-network
